### ISSUE TITLE
Improving Typescript usability?

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#10]
Is your feature request related to a problem? Please describe.
MST sounds awesome. However, I've tried a couple times to start using MST in my TS codebases, but invariably abandon due to Typescript issues (at least as far as I know, and I don't know much).

A few examples:

Circular references in structure need casts sprinkled at all use sites.
Can't reference self.otherAction() from an action (again, without casts sprinkled).
Can't accept nor return recursive/self types in actions/views.
Slow type inference.
Large, cryptic type errors.
Spotty type-checking (sorry I know this is vague, but this is what I seem to have experienced).
Flow generators are non-standard and thus don't benefit from things like tslint's no-floating-promise.
Some other things I'm forgetting (might be useful to have a roundup that's more complete than what's in the README currently).
There are also opportunities for improved typing, such as models defaulting to read-only types outside of actions.

Describe the solution you'd like
I understand that some of these are chalked up to Typescript's limitations, but IMO improved TS usability is a worthy target given TS's momentum. At least for this user, TS usability is the main immediate barrier to adoption.

A different approach from embedded type system is code generation. Various GraphQL tools use this approach, as a random example.

I know this doesn't solve everything, e.g. flow generators, but I imagine it would be a big step up.

Downsides include more frontend infrastructure needed to execute code generation.

Describe alternatives you've considered

Using MobX directly, but then you can't have the nice things MST brings.
Casting everywhere.
Perhaps a layer of indirection in MST that applies some forceful casting at the right places, so that the types exposed to the user are "clean." I haven't thought this through enough, but I suspect this may be intractable.
Are you willing to (attempt) a PR?
You wouldn't want a change like this in my hands....

**Comment by coolsoftwaretyler** [comment]
Whoops, also should not actually get moved. It got caught up in the issue migration because it matches middleware when searching open issue. Closing here.
