### ISSUE TITLE
decorate passTrough values 

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#13]
we should support both ways decorate and addMiddleware(node...) the pass trough option described later might therefore be way to improve that.

.as I think the demand is increasing
e.g. https://github.com/mobxjs/mobx-state-tree/issues/621 ~, @tim-field on gitter, undoManger

for that, we can get the attached middlewares of an action within a middleware or within flows (e.g. if an action passed as a parameter). Also, it would solve the problem that lifecycle hook actions are passed to middlewares.

That would mean that we kind of should be able to attach flows or any other custom middleware declaratively and therefore "tag" the actions before the invocation. this though would mean that we'd have to attach the middleware to an action itself / multiple actions and find a syntax for that so that does not get too verbose.

example (bad example just to illustrate the idea):

```
actions(‘groupName’, self => {
        setName({ name }) {
            self.name = name
        },
        setAge(age) {
            self.age = age
        }
}).middlewares(self => ({
        // of course addMiddleware would be hidden
        addMiddleware(self.groupName, undoManger.withoutUndo)
})
```
a downside/ upside (not sure yet) of this could be that we'd also have to declaratively add the opponent e.g. using
withoutUndo for one group
withUndo for the other group
unless we'd keep the node middleware too as a default

**Comment by coolsoftwaretyler** [comment]
I think this is also mst-specific, not for middlewares. Closing!
