### ISSUE TITLE
applyAction with async result

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#14]
Given an async action (borrowed from https://github.com/mobxjs/mobx-state-tree/blob/master/docs/async-actions.md#asynchronous-actions-and-middleware)
```

const Store = types.model({
        githubProjects: types.array(types.frozen),
        state: types.enumeration("State", ["pending", "done", "error"])
    })
    .actions(self => ({
        fetchProjects: process(function* fetchProjects() { // <- note the star, this a generator function!
            self.githubProjects = []
            self.state = "pending"
            try {
                // ... yield can be used in async/await style
                self.githubProjects = yield fetchGithubProjectsSomehow()
                self.state = "done"
            } catch (e) {
                // ... including try/catch error handling
                console.error("Failed to fetch projects", error)
                self.state = "error"
            }
        })
    }))

const store = Store.create({})
// async actions will always return a promise resolving to the returned value
store.fetchProjects().then(() => {
    console.log("done")
})

```
How would one apply this action using applyAction() and await the result? The signature for apply action is:

`export declare function applyAction(target: IStateTreeNode, actions: ISerializedActionCall | ISerializedActionCall[]): void;`

It would be nice if it could be made async:

`export declare function applyAction<T>(target: IStateTreeNode, actions: ISerializedActionCall | ISerializedActionCall[]): Promise<T>;`

Then we can call:

```
applyAction(store, {name: "fetchProjects"}).then(() => {
    console.log("done")
})
```
Obviously this is a contrived example, but if you have a deeply nested tree it becomes useful.

**Comment by coolsoftwaretyler** [comment]
Whoops, this one is also mst-specific. Sorry about that. Closing.
