### ISSUE TITLE
Reference invalidation when undoing array replace operation #2006

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#3]
Bug report
I am trying to re-order items in the array and using replace function for this. There is a safe reference to one of the array items in the model. When action is performed everything works as expected but when I try to undo using UndoRedoMiddleware reference gets invalidated and I get warnings in console regarding access to elements which were removed from the tree. How can I avoid this issue? Reference have to be invalidated if referenced item is removed from array.

 I've checked documentation and searched for existing issues
 I've made sure my project is based on the latest MST version
Sandbox link or minimal reproduction code
https://codesandbox.io/s/sharp-tom-d44g8e?file=/src/index.js

Describe the expected behavior
Reference should remain valid after undo operation and there should be no warnings

Describe the observed behavior
Reference invalidated on undo and there is warning in console regarding access to removed node

**Comment by coolsoftwaretyler** [comment]
I think this one was incorrectly tagged, and is actually an upstream bug in MST. I'm going to close this since mst-middlewares can't fix it. Thanks!
