### ISSUE TITLE
Middlewares can not detect modification directly made in the parent action 

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#5]
Bug report

 I've checked documentation and searched for existing issues
 I've made sure my project is based on the latest MST version
 Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.
Description
The documentation on addMiddleware says

Middleware can be used to intercept any action is invoked on the subtree where it is attached. If a tree is protected (by default), this means that any mutation of the tree will pass through your middleware.
However, this is not true. When the parent action modify the child directly, the middleware cannot detect the action.
This either needs to be fixed. Or at least the function documentation needs to be updated to reflect the actual behavior.

Sandbox link or minimal reproduction code
[sandbox](https://codesandbox.io/s/mobx-state-tree-todolist-forked-xtfoxh?file=/index.js)

Describe the expected behavior
Click on "modify from parent".
Console should print "action detected"

Describe the observed behavior
Click on "modify from parent".
Console did not print "action detected"

**Comment by coolsoftwaretyler** [comment]
This is actually just a docs issue in MST, not for mst-middlewares. Going to close here and re-tag in MST. Thanks!
