### ISSUE TITLE
Make preSnapshot and postSnapshot actions in middleware ? 

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#6]
Feature request
Make implementing preSnapshot and postSnapshot implementable by middleware.

Is your feature request related to a problem? Please describe.

I have some models that describe user files. In order to serialize this data I need to access some global state that I might want to redefine depending on the environment. (E.x., A database interface, a file interface). In order to do this now I would have to set up a complicated set of model builders that take my interface as arguments and build the models.
Sometimes I would like to serialize/deserialize a node based on information in the parent.
It would be nice to be able to globally change how serialization is handled for other reasons. For example, I have a lot of models that are optional and those are automatically serialized as null when empty instead of just being omitted. With a middleware I could globally change that behavior without having to add processors to every model or request the change in MST.
See also: https://github.com/mobxjs/mobx-state-tree/issues/662

Describe the solution you'd like
Currently, middleware does not get the preSnapshot or postSnapshot actions.

Report those actions to middleware.
Use the snapshot returned by the middleware to serialize/deserialize.
Describe alternatives you've considered

Manually applying pre/post snapshot to every model.
Generating models in functions.
Are you willing to (attempt) a PR?

 Yes
 No
 Maybe

**Comment by coolsoftwaretyler** [comment]
Whoops, that's my bad. This is also a MST problem, the request was to add some hooks into the middlewares infrastructure to provide snapshots to middlewares downstream. Closing here, leaving in MST.
