### ISSUE TITLE
Child models' lifecycle methods not firing until property access of node

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#7]
Bug report

 I've checked documentation and searched for existing issues
 I've made sure my project is based on the latest MST version
 Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.
Sandbox link or minimal reproduction code
[Sandbox Link](https://codesandbox.io/s/mobx-state-tree-afterhooks-bug-wgj4h)

Potentially related to https://github.com/mobxjs/mobx-state-tree/issues/1665.

Describe the expected behavior
The afterCreate and afterAttach hooks of the Child model should fire after the Root model creates it as part of its own tree.

Describe the observed behavior
The afterCreate and afterAttach hooks of the Child model do not fire automatically after creation/attachment by the Root model.

Of the two example Root models in the Sandbox:

Root simply creates a Child instance for its child property, but the afterCreate/Attach lifecycle hooks of the Child don't fire.
RootWithAccess is identical to Root however instead we perform a (rather useless) property access self.child to access the Child instance, which oddly enough flushes the seemingly pending afterCreate/Attach lifecycle hooks. (as can be seen with console logs) — as if MST isn't flushing these pending actions until some kind of property access.

**Comment by coolsoftwaretyler** [comment]
This was caught up in an issue migration since middlewares were mentioned, but should be resolved with https://github.com/mobxjs/mobx-state-tree/pull/1952. Closing here!
