### ISSUE TITLE
createActionTrackingMiddleware breaks with nested flows

### ISSUE THREAD

**Issue by zuhorer** [coolsoftwaretyler/mst-middlewares#8]
Bug report

 I've checked documentation and searched for existing issues
 I've made sure my project is based on the latest MST version
 Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.
Sandbox link or minimal reproduction code
https://codesandbox.io/s/oo8rj418z9

Describe the expected behavior
There should be no issue with using middleware from createActionTrackingMiddleware with nested flows

Describe the observed behavior
There is always an error due to the middleware usage for nested flow actions (you'll have to open up chrome dev console or the equivalent to see the error):
image

I believe this issue is from the fact that the action middleware will remove the rootId on delete (which will remove the action context that the outside flow still depends on). Instead the action middleware should delete the call.parentId

https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/middlewares/create-action-tracking-middleware.ts#L86

**Comment by coolsoftwaretyler** [comment]
I think this is actually related to the internal middleware code in MST itself, closing out here. Sorry for the runaround!
